#!/bin/bash

# Copyright 2012 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# loc:/opt/google/chrome-remote-desktop/is-remoting-session

# Test whether or not the current desktop is virtual Me2Me.

[ -n "$CHROME_REMOTE_DESKTOP_SESSION" ]
